
/**
 ** Please don't modify this file.
 ** This file was generated by the EntireX Java Wrapper
 ** from the IDL file NTDEVOPS.idl.
 **
 ** @author    Software AG
 ** @version   EntireX Wrapper, Version: 10.3.0.0.640, Date: 28 Aug 2018 (1.172)
 ** Generated: 2021-10-07 13:32:43.759 +0200
 **/

import java.lang.reflect.Method;
import java.math.BigDecimal;

import com.softwareag.entirex.aci.*;

public class Ntdevops extends RPCService {

	public static final String DEFAULT_BROKERID = "ETB038.99g.giss.ss:10100";
	public static final String DEFAULT_SERVER = "RPC/NTSILTGA/CALLNAT";

	private Pocnhij1Pocqhij1_s pocnhij1Pocqhij1_s;

	private final static String POCNHIJ1_FORMAT = // from IDL
			("OG1,1ON5,0ON5,0ON2,0OG1,0SG1,1SN10,0SG1,0.");

	private Pocnhij3Pocqhij3_s pocnhij3Pocqhij3_s;

	private final static String POCNHIJ3_FORMAT = // from IDL
			("OG1,1ON5,0ON5,0OG1,0SG1,1SN10,0SG1,0.");

	public Ntdevops() {
		super();
	}

	public Ntdevops(Broker broker) {
		this(broker, DEFAULT_SERVER);
	}

	public Ntdevops(BrokerService bs) {
		this(bs.getBroker(), bs.toString());
	}

	public Ntdevops(Broker broker, String serverAddr) {
		super(broker, serverAddr, "NTDEVOPS", true);
	}

	public static String getStubVersion() {
		return "EntireX RPC for Java Stub Version=10.3.0.0, Patch Level=640";
	}

	public Pocnhij1Pocqhij1_s getPocnhij1Pocqhij1_s() {
		return this.pocnhij1Pocqhij1_s;
	}

	public void pocnhij1(Ntdevops.Pocnhij1Pocqhij1_e pocqhij1_e) throws BrokerException {

		enterStub();
		buildHeader(POCNHIJ1_FORMAT, "8", 0, 11, "POCNHIJ1", true, 1110, true, false, 2050);
		if (getVersion() >= 2000) {

			if (pocqhij1_e == null) {
				new Pocnhij1Pocqhij1_e().add();
			} else {
				pocqhij1_e.add();
			}
		} else {
			super.marshal.addDataN(pocqhij1_e.sumatorio_1, 5, 0);
			super.marshal.addDataN(pocqhij1_e.sumatorio_2, 5, 0);
			super.marshal.addDataN(pocqhij1_e.multiplicador, 2, 0);
			if (!super.compression) {
				super.marshal.addDataN(new BigDecimal(0), 10, 0);
			}
		}

		callServer();

		if (getVersion() >= 2000) {
			if (pocnhij1Pocqhij1_s == null)
				pocnhij1Pocqhij1_s = new Pocnhij1Pocqhij1_s();
			pocnhij1Pocqhij1_s.get();
		} else {
			if (!super.compression) {
				super.marshal.skipData(6);
			}
			if (!super.compression) {
				super.marshal.skipData(6);
			}
			if (!super.compression) {
				super.marshal.skipData(3);
			}
			if (pocnhij1Pocqhij1_s == null) {
				pocnhij1Pocqhij1_s = new Pocnhij1Pocqhij1_s();
			}
			pocnhij1Pocqhij1_s.resultado = super.marshal.getDataN(10, 0);
		}
		leaveStub();

	}

	public Pocnhij3Pocqhij3_s getPocnhij3Pocqhij3_s() {
		return this.pocnhij3Pocqhij3_s;
	}

	public void pocnhij3(Ntdevops.Pocnhij3Pocqhij3_e pocqhij3_e) throws BrokerException {

		enterStub();
		buildHeader(POCNHIJ3_FORMAT, "7", 0, 11, "POCNHIJ3", true, 1110, true, false, 2050);
		if (getVersion() >= 2000) {

			if (pocqhij3_e == null) {
				new Pocnhij3Pocqhij3_e().add();
			} else {
				pocqhij3_e.add();
			}
		} else {
			super.marshal.addDataN(pocqhij3_e.minuendo, 5, 0);
			super.marshal.addDataN(pocqhij3_e.sustraendo, 5, 0);
			if (!super.compression) {
				super.marshal.addDataN(new BigDecimal(0), 10, 0);
			}
		}

		callServer();

		if (getVersion() >= 2000) {
			if (pocnhij3Pocqhij3_s == null)
				pocnhij3Pocqhij3_s = new Pocnhij3Pocqhij3_s();
			pocnhij3Pocqhij3_s.get();
		} else {
			if (!super.compression) {
				super.marshal.skipData(6);
			}
			if (!super.compression) {
				super.marshal.skipData(6);
			}
			if (pocnhij3Pocqhij3_s == null) {
				pocnhij3Pocqhij3_s = new Pocnhij3Pocqhij3_s();
			}
			pocnhij3Pocqhij3_s.resultado = super.marshal.getDataN(10, 0);
		}
		leaveStub();

	}

	public class Pocnhij1Pocqhij1_e {
		public BigDecimal sumatorio_1;
		public BigDecimal sumatorio_2;
		public BigDecimal multiplicador;

		public void setSumatorio_1(BigDecimal sumatorio_1) {
			this.sumatorio_1 = sumatorio_1;
		}

		public BigDecimal getSumatorio_1() {
			return this.sumatorio_1;
		}

		public void setSumatorio_2(BigDecimal sumatorio_2) {
			this.sumatorio_2 = sumatorio_2;
		}

		public BigDecimal getSumatorio_2() {
			return this.sumatorio_2;
		}

		public void setMultiplicador(BigDecimal multiplicador) {
			this.multiplicador = multiplicador;
		}

		public BigDecimal getMultiplicador() {
			return this.multiplicador;
		}

		public void add() throws BrokerException {

			if (sumatorio_1 == null) {
				Ntdevops.super.marshal.addDataN(null, 5, 0);
			} else {
				Ntdevops.super.marshal.addDataN(sumatorio_1, 5, 0);
			}

			if (sumatorio_2 == null) {
				Ntdevops.super.marshal.addDataN(null, 5, 0);
			} else {
				Ntdevops.super.marshal.addDataN(sumatorio_2, 5, 0);
			}

			if (multiplicador == null) {
				Ntdevops.super.marshal.addDataN(null, 2, 0);
			} else {
				Ntdevops.super.marshal.addDataN(multiplicador, 2, 0);
			}
		}

	}

	public class Pocnhij1Pocqhij1_s {
		public BigDecimal resultado;

		public void setResultado(BigDecimal resultado) {
			this.resultado = resultado;
		}

		public BigDecimal getResultado() {
			return this.resultado;
		}

		public void get() throws BrokerException {
			resultado = Ntdevops.super.marshal.getDataN(10, 0);
		}
	}

	public class Pocnhij3Pocqhij3_e {
		public BigDecimal minuendo;
		public BigDecimal sustraendo;

		public void setMinuendo(BigDecimal minuendo) {
			this.minuendo = minuendo;
		}

		public BigDecimal getMinuendo() {
			return this.minuendo;
		}

		public void setSustraendo(BigDecimal sustraendo) {
			this.sustraendo = sustraendo;
		}

		public BigDecimal getSustraendo() {
			return this.sustraendo;
		}

		public void add() throws BrokerException {

			if (minuendo == null) {
				Ntdevops.super.marshal.addDataN(null, 5, 0);
			} else {
				Ntdevops.super.marshal.addDataN(minuendo, 5, 0);
			}

			if (sustraendo == null) {
				Ntdevops.super.marshal.addDataN(null, 5, 0);
			} else {
				Ntdevops.super.marshal.addDataN(sustraendo, 5, 0);
			}
		}

	}

	public class Pocnhij3Pocqhij3_s {
		public BigDecimal resultado;

		public void setResultado(BigDecimal resultado) {
			this.resultado = resultado;
		}

		public BigDecimal getResultado() {
			return this.resultado;
		}

		public void get() throws BrokerException {
			resultado = Ntdevops.super.marshal.getDataN(10, 0);
		}
	}

	public static final Method enterStubMethod = getStubMethod("enterClientStub");
	public static final Method leaveStubMethod = getStubMethod("leaveClientStub");

	private static Method getStubMethod(String name) {
		Method method = null;
		try {
			method = RPCService.class.getMethod(name, (Class<?>[]) null);
		} catch (final Exception ex) {
		}
		return method;
	}

	private void enterStub() {
		if (enterStubMethod != null) {
			try {
				enterStubMethod.invoke(this, (Object[]) null);
			} catch (final Exception ex) {
			}
		}
	}

	private void leaveStub() {
		if (leaveStubMethod != null) {
			try {
				leaveStubMethod.invoke(this, (Object[]) null);
			} catch (final Exception ex) {
			}
		}
	}
}
